attached = true
name = "code"
layout = "main-horizontal"
[[hooks]]
  command = 'run-shell -t code:0 "tmux select-pane -t 0 && tmux rename-session \"Code $((RANDOM))\" && tmux setw synchronize-panes on"' 
  name = "client-attached"

[[windows]]
  name = ""
  [[windows.panes]]
  commands = []
  start_directory = "~/.local/code"

  [[windows.panes]]
  commands = ["clear"]
  start_directory = "~/.local/code"

  [[windows.panes]]
  commands = ["tmux resize-pane -D 15 && clear"]
  start_directory = "~/.local/code"
