attached = true
name = "code"
layout = "main-horizontal"
# terminal_multiplexer = "tmux-rs"

[[hooks]]
  command = 'run-shell -t code:0 "tmux select-pane -t 0 && tmux setw synchronize-panes on"' 
  name = "client-attached"

[[windows]]
  name = ""
  [[windows.panes]]
  commands = []
  start_directory = "~/.local/code"

  [[windows.panes]]
  commands = ["clear"]
  start_directory = "~/.local/code"

  [[windows.panes]]
  commands = ["tmux resize-pane -t 1 -y 15% && clear"]
  start_directory = "~/.local/code"
