attached = true
name = "multi"
layout = "92fd,168x42,0,0{83x42,0,0[83x13,0,0,0,83x13,0,14,1,83x14,0,28,2],84x42,84,0[84x13,84,0,3,84x13,84,14,4,84x14,84,28,5]}"
# layout = "tiled"
# terminal_multiplexer = "tmux-rs"

[[hooks]]
  command = 'run-shell -t multi:0 "tmux select-pane -t 0"' 
  name = "client-attached"

[[windows]]
  name = "✖"
  [[windows.panes]]
  commands = []

  [[windows.panes]]
  commands = []

  [[windows.panes]]
  commands = ["ssh ash"]

  [[windows.panes]]
  commands = ["ssh deskg"]

  [[windows.panes]]
  commands = ["ssh lapn"]

  [[windows.panes]]
  commands = ["ssh kandarian"]
