attached = true
name = "single"
[[hooks]]
  command = 'run-shell -t single:0 "tmux rename-session \"S $((RANDOM))\""' 
  name = "client-attached"

[[windows]]
  name = "☝"
  [[windows.panes]]
  commands = []

