name: Multi
startup_pane: 0
windows:
  - ✖:
      layout: 92fd,168x42,0,0{83x42,0,0[83x13,0,0,0,83x13,0,14,1,83x14,0,28,2],84x42,84,0[84x13,84,0,3,84x13,84,14,4,84x14,84,28,5]}
      panes:
        -  #local
        -  #local
        - ash:
            - ssh Ash
        - lg:
            - ssh lapg
        - na:
            - ssh lapn
        - dn:
            - ssh pi
