local M = {
  { 'xzbdmw/colorful-menu.nvim', enabled = true },
  {
    'saghen/blink.cmp',
    enabled = true,
  },
  {
    'stevearc/conform.nvim',
    opts = {
      formatters_by_ft = {
        javascript = { 'prettier' },
        typescript = { 'prettier' },
        javascriptreact = { 'prettier' },
        typescriptreact = { 'prettier' },
        css = { 'prettier' },
        html = { 'prettier' },
        json = { 'prettier' },
        yaml = { 'prettier' },
        markdown = { 'prettier' },
        bash = { 'shfmt' },
        sh = { 'shfmt' },
        zsh = { 'shfmt' },
        lua = { 'stylua' },
        golang = { 'gofumpt' },
        python = { 'isort', 'black' },
      },

      formatters = {
        prettier = {
          prepend_args = { '--single-quote', '--jsx-single-quote' },
        },
      },
    },
  },
  { 'lewis6991/gitsigns.nvim', enabled = true },
  { 'nvim-lualine/lualine.nvim', enabled = true },
  { 'neovim/nvim-lspconfig', enabled = true },
  { 'OXY2DEV/markview.nvim', enabled = true },
  {
    'williamboman/mason-lspconfig.nvim',
    enabled = true,
    opts = {
      ensure_installed = {
        'bashls',
        'html',
        'ts_ls',
        'cssls',
        'tailwindcss',
        'graphql',
        'emmet_ls',
        'pyright',
        'jsonls',
        'yamlls',
        'lua_ls',
        'marksman',
        'gopls',
        'taplo',
      },
    },
  },
  {
    'WhoIsSethDaniel/mason-tool-installer.nvim',
    opts = {
      ensure_installed = {
        'prettier',
        'eslint',
        'shellcheck',
        'shfmt',
        'jsonlint',
        'stylua',
        'isort',
        'black',
        'pylint',
        'yamllint',
        'markdownlint',
        'golangci-lint',
        'gofumpt',
      },
    },
  },
  { 'nvim-mini/mini.ai', enabled = true },
  { 'nvim-mini/mini.surround', enabled = true },
  { 'folke/noice.nvim', enabled = true },
  { 'willothy/nvim-cokeline', enabled = true },
  { 'NvChad/nvim-colorizer.lua', enabled = true },
  {
    'mfussenegger/nvim-lint',
    opts = {
      linters_by_ft = {
        markdown = { 'markdownlint' },
        php = { 'php' },
        yaml = { 'yamllint' },
        javascript = { 'eslint' },
        json = { 'jsonlint' },
        typescript = { 'eslint' },
        javascriptreact = { 'eslint' },
        typescriptreact = { 'eslint' },
        bash = { 'shellcheck' },
        go = { 'golangcilint' },
        python = { 'flake8' },
        lua = { 'luacheck' },
      },

      linter_args = {
        luacheck_args = {
          '--formatter',
          'plain',
          '--codes',
          '--ranges',
          '--globals = vim',
          '-',
        },
      },
    },
  },
  {
    'nvim-treesitter/nvim-treesitter',
    opts = {
      highlight = {
        enable = true,
      },
      indent = { enable = true },
      ensure_installed = {
        'json',
        'javascript',
        'typescript',
        'tsx',
        'yaml',
        'html',
        'php',
        'css',
        'markdown',
        'markdown_inline',
        'bash',
        'lua',
        'vim',
        'python',
        'dockerfile',
        'gitignore',
        'go',
        'qmljs',
        'qmldir',
        'query',
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = '<C-space>',
          node_incremental = '<C-space>',
          scope_incremental = false,
          node_decremental = '<bs>',
        },
      },
    },
  },
  { 'hedyhli/outline.nvim', enabled = true },
  { 'HiPhish/rainbow-delimiters.nvim', enabled = true },
  { 'christoomey/vim-tmux-navigator', enabled = true },
  {
    'folke/which-key.nvim',
    opts = {
      spec = {
        {
          { '<leader>m', group = 'Markdown' },
        },
      },
    },
  },
  { 'natecraddock/workspaces.nvim', enabled = true },
}
return M
