import = [
  "~/.config/alacritty/alacritty-theme/themes/gruvbox_material_medium_dark.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001\""
key = "O"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001%"
key = "E"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001o"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001;"
key = "Tab"
mods = "Control|Shift"

# [[keyboard.bindings]]
# action = "ScrollLineUp"
# key = "PageUp"
# 
# [[keyboard.bindings]]
# action = "ScrollLineDown"
# key = "PageDown"
# 
# [[keyboard.bindings]]
# action = "ScrollPageDown"
# key = "PageDown"
# mods = "Control"
# 
# [[keyboard.bindings]]
# action = "ScrollPageUp"
# key = "PageUp"
# mods = "Control"
