import = [
  "~/.config/alacritty/alacritty-theme/themes/gruvbox_material_medium_dark.toml",
  "~/.config/alacritty/bindings.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 15

[window]
padding = {x = 3, y = 3}
blur = true

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

